download_url: https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
replication_url: https://planet.openstreetmap.org/replication/hour/
replication_interval: 1h
piano_domains:
- a.piano.tiles.data.gouv.fr
- b.piano.tiles.data.gouv.fr
- c.piano.tiles.data.gouv.fr
forte_domains:
- a.forte.tiles.data.gouv.fr
- b.forte.tiles.data.gouv.fr
- c.forte.tiles.data.gouv.fr
ssl: true
psql_version: 10
